Rebol []

get-red-type: func[type /local res][
	replace type "const " ""
	replace type "struct " ""
	trim/all type
	res: select type-map type
	unless res [
		print ["!!!! " mold type]
		append err type
		if type = "const void" [
		;	halt
		]

	]
	any [res mold type]
]

ch_hexdigit: charset [#"0" - #"9" #"a" - #"f" #"A" - #"F"]
ch_name: charset [#"a" - #"z" #"A" - #"Z" #"0" - #"9" #"_"]
ch_space: charset " ^-^/^M"


args: copy []

num-def: 0
num-imp: 0
num-prc: 0

err: []
procedures: []

pad: func[value len][
	value: either block? value [rejoin value][copy value]
	len: len - length? value
	if len > 0 [
		insert/dup tail value #" " len
	]
	value
]

pad-en: func[en /local s][pad en 43]


type-map: [
"BOOL"                                      "logic!"
"BOOL*"                                     "logic-ptr!"
"char*"                                     "c-string!"
"char**"                                    "string-ptr!"
"char***"                                   "string-ptr-ptr!"
"charconst*"                                "c-string!"
"charconst**"                               "string-ptr!"
"cl_context"                                "pointer! [integer!]"
"cl_event"                                  "pointer! [integer!]"
"Colormap"                                  "XColormap!"
"Display*"                                  "XDisplay!"
"double"                                    "float!"
"double*"                                   "pointer! [float!]"
"DWORD"                                     "integer!"
"DWORD*"                                    "pointer! [integer!]"
"EGLAttrib"                                 "EGLAttrib!"
"EGLAttrib*"                                "EGLAttrib-ptr!"
"EGLAttribKHR*"                             "EGLAttribKHR-ptr!"
"EGLBoolean"                                "EGLBoolean!"
"EGLBoolean*"                               "EGLBoolean-ptr!"
"EGLClientBuffer"                           "EGLClientBuffer!"
"EGLClientPixmapHI*"                        "EGLClientPixmapHI!"
"EGLConfig"                                 "EGLConfig!"
"EGLConfig*"                                "EGLConfig-ptr!"
"EGLContext"                                "EGLContext!"
"EGLDEBUGPROCKHR"                           "EGLDEBUGPROCKHR!"
"EGLDeviceEXT"                              "EGLDeviceEXT!"
"EGLDeviceEXT*"                             "EGLDeviceEXT-ptr!"
"EGLDisplay"                                "EGLDisplay!"
"EGLenum"                                   "EGLenum!"
"EGLGetBlobFuncANDROID"                     "EGLGetBlobFuncANDROID!"
"EGLImage"                                  "EGLImage!"
"EGLImageKHR"                               "EGLImageKHR!"
"EGLint"                                    "EGLint!"
"EGLint*"                                   "EGLint-ptr!"
"EGLLabelKHR"                               "EGLLabelKHR!"
"EGLNativeDisplayType"                      "EGLNativeDisplayType!"
"EGLNativeDisplayType*"                     "EGLNativeDisplayType-ptr!"
"EGLNativeFileDescriptorKHR"                "EGLNativeFileDescriptorKHR!"
"EGLNativePixmapType"                       "EGLNativePixmapType!"
"EGLNativePixmapType*"                      "EGLNativePixmapType-ptr!"
"EGLNativeWindowType"                       "EGLNativeWindowType!"
"EGLNativeWindowType*"                      "EGLNativeWindowType-ptr!"
"EGLnsecsANDROID"                           "EGLnsecsANDROID!"
"EGLObjectKHR"                              "EGLObjectKHR!"
"EGLOutputLayerEXT"                         "EGLOutputLayerEXT!"
"EGLOutputLayerEXT*"                        "EGLOutputLayerEXT-ptr!"
"EGLOutputPortEXT"                          "EGLOutputPortEXT!"
"EGLOutputPortEXT*"                         "EGLOutputPortEXT-ptr!"
"EGLSetBlobFuncANDROID"                     "EGLSetBlobFuncANDROID!"
"EGLStreamKHR"                              "EGLStreamKHR!"
"EGLSurface"                                "EGLSurface!"
"EGLSync"                                   "EGLSync!"
"EGLSyncKHR"                                "EGLSyncKHR!"
"EGLSyncNV"                                 "EGLSyncNV!"
"EGLTime"                                   "EGLTime!"
"EGLTimeKHR"                                "EGLTimeKHR!"
"EGLTimeKHR*"                               "EGLTimeKHR-ptr!"
"EGLTimeNV"                                 "EGLTimeNV!"
"EGLuint64KHR*"                             "EGLuint64KHR-ptr!"
"EGLuint64NV"                               "EGLuint64NV!"
"float"                                     "float32!"
"float*"                                    "pointer! [float32!]"
"Font"                                      "Font!"
"GLbitfield"                                "GLbitfield!"
"GLboolean"                                 "GLboolean!"
"GLboolean*"                                "pointer! [integer!]"
"GLboolean**"                               "GLboolean-ptr!"
"GLbyte"                                    "GLbyte!"
"GLbyte*"                                   "pointer! [GLbyte!]"
"GLchar*"                                   "GLstring!"
"GLchar*const*"                             "GLstring-ptr!"
"GLcharARB*"                                "GLcharARB-ptr!"
"GLcharARB**"                               "GLcharARB-ptr-ptr!"
"GLclampd"                                  "GLclampd!"
"GLclampd*"                                 "pointer! [GLclampd!]"
"GLclampf"                                  "GLclampf!"
"GLclampf*"                                 "pointer! [GLclampf!]"
"GLclampx"                                  "GLclampx!"
"GLDEBUGPROC"                               "GLDEBUGPROC!"
"GLDEBUGPROCAMD"                            "GLDEBUGPROCAMD!"
"GLDEBUGPROCARB"                            "GLDEBUGPROCARB!"
"GLdouble"                                  "GLdouble!"
"GLdouble*"                                 "pointer! [GLdouble!]"
"GLeglClientBufferEXT"                      "GLeglClientBufferEXT!"
"GLenum"                                    "GLenum!"
"GLenum*"                                   "pointer! [GLenum!]"
"GLfixed"                                   "GLfixed!"
"GLfixed*"                                  "pointer! [GLfixed!]"
"GLfloat"                                   "GLfloat!"
"GLfloat*"                                  "pointer! [GLfloat!]"
"GLFWcharfun"                               "GLFWcharfun!"
"GLFWcharmodsfun"                           "GLFWcharmodsfun!"
"GLFWcursor*"                               "GLFWcursor!"
"GLFWcursorenterfun"                        "GLFWcursorenterfun!"
"GLFWcursorposfun"                          "GLFWcursorposfun!"
"GLFWdropfun"                               "GLFWdropfun!"
"GLFWerrorfun"                              "GLFWerrorfun!"
"GLFWframebuffersizefun"                    "GLFWframebuffersizefun!"
"GLFWgammaramp*"                            "GLFWgammaramp!"
"GLFWglproc"                                "GLFWglproc!"
"GLFWimage*"                                "GLFWimage!"
"GLFWjoystickfun"                           "GLFWjoystickfun!"
"GLFWkeyfun"                                "GLFWkeyfun!"
"GLFWmonitor*"                              "GLFWmonitor!"
"GLFWmonitor**"                             "GLFWmonitor-ptr!"
"GLFWmonitorfun"                            "GLFWmonitorfun!"
"GLFWmousebuttonfun"                        "GLFWmousebuttonfun!"
"GLFWscrollfun"                             "GLFWscrollfun!"
"GLFWvidmode*"                              "GLFWvidmode!"
"GLFWvkproc"                                "GLFWvkproc!"
"GLFWwindow*"                               "GLFWwindow!"
"GLFWwindowclosefun"                        "GLFWwindowclosefun!"
"GLFWwindowfocusfun"                        "GLFWwindowfocusfun!"
"GLFWwindowiconifyfun"                      "GLFWwindowiconifyfun!"
"GLFWwindowposfun"                          "GLFWwindowposfun!"
"GLFWwindowrefreshfun"                      "GLFWwindowrefreshfun!"
"GLFWwindowsizefun"                         "GLFWwindowsizefun!"
"GLhalf"                                    "GLhalf!"
"GLhalf*"                                   "GLhalf-ptr!"
"GLhandleARB"                               "GLhandleARB!"
"GLhandleARB*"                              "pointer! [GLhandleARB!]"
"GLint"                                     "GLint!"
"GLint*"                                    "pointer! [GLint!]"
"GLint64"                                   "GLint64!"
"GLint64*"                                  "GLint64-ptr!"
"GLint64EXT"                                "GLint64EXT!"
"GLint64EXT*"                               "GLint64EXT-ptr!"
"GLintptr"                                  "GLintptr!"
"GLintptr*"                                 "pointer! [GLintptr!]"
"GLintptrARB"                               "GLintptrARB!"
"GLLOGPROCREGAL"                            "GLLOGPROCREGAL!"
"GLshort"                                   "GLshort!"
"GLshort*"                                  "GLshort-ptr!"
"GLsizei"                                   "GLsizei!"
"GLsizei*"                                  "pointer! [GLsizei!]"
"GLsizeiptr"                                "GLsizeiptr!"
"GLsizeiptr*"                               "pointer! [GLsizeiptr!]"
"GLsizeiptrARB"                             "GLsizeiptrARB!"
"GLsync"                                    "GLsync!"
"GLubyte"                                   "GLubyte!"
"GLubyte*"                                  "pointer! [GLubyte!]"
"GLuint"                                    "GLuint!"
"GLuint*"                                   "pointer! [GLuint!]"
"GLuint64"                                  "GLuint64!"
"GLuint64*"                                 "GLuint64-ptr!"
"GLuint64EXT"                               "GLuint64EXT!"
"GLuint64EXT*"                              "GLuint64EXT-ptr!"
"GLulong"                                   "GLuint!"
"GLushort"                                  "GLushort!"
"GLushort*"                                 "GLushort-ptr!"
"GLvdpauSurfaceNV"                          "GLvdpauSurfaceNV!"
"GLvdpauSurfaceNV*"                         "pointer! [GLvdpauSurfaceNV!]"
"GLvoid*"                                   "pointer! [byte!]"
"GLVULKANPROCNV"                            "GLVULKANPROCNV!"
"GLXContext"                                "GLXContext!"
"GLXContextID"                              "GLXContextID!"
"GLXDrawable"                               "GLXDrawable!"
"GLXFBConfig"                               "GLXFBConfig!"
"GLXFBConfig*"                              "GLXFBConfig-ptr!"
"GLXFBConfigSGIX"                           "GLXFBConfigSGIX!"
"GLXFBConfigSGIX*"                          "GLXFBConfigSGIX-ptr!"
"GLXHyperpipeConfigSGIX*"                   "GLXHyperpipeConfigSGIX-ptr!"
"GLXHyperpipeNetworkSGIX*"                  "GLXHyperpipeNetworkSGIX-ptr!"
"GLXPbuffer"                                "GLXPbuffer!"
"GLXPixmap"                                 "GLXPixmap!"
"GLXVideoCaptureDeviceNV"                   "GLXVideoCaptureDeviceNV!"
"GLXVideoCaptureDeviceNV*"                  "GLXVideoCaptureDeviceNV-ptr!"
"GLXVideoDeviceNV"                          "GLXVideoDeviceNV!"
"GLXVideoDeviceNV*"                         "GLXVideoDeviceNV-ptr!"
"GLXWindow"                                 "GLXWindow!"
"HANDLE"                                    "handle!"
"HANDLE*"                                   "handle-ptr!"
"HDC"                                       "HDC!"
"HGLRC"                                     "HGLRC!"
"HGPUNV"                                    "HGPUNV!"
"HGPUNV*"                                   "HGPUNV-ptr!"
"HPBUFFERARB"                               "HPBUFFERARB!"
"HPBUFFEREXT"                               "HPBUFFEREXT!"
"HPVIDEODEV"                                "HPVIDEODEV!"
"HPVIDEODEV*"                               "HPVIDEODEV-ptr!"
"HVIDEOINPUTDEVICENV"                       "HVIDEOINPUTDEVICENV!"
"HVIDEOINPUTDEVICENV*"                      "HVIDEOINPUTDEVICENV-ptr!"
"HVIDEOOUTPUTDEVICENV"                      "HVIDEOOUTPUTDEVICENV!"
"HVIDEOOUTPUTDEVICENV*"                     "HVIDEOOUTPUTDEVICENV-ptr!"
"int"                                       "integer!"
"int*"                                      "pointer! [integer!]"
"INT32*"                                    "pointer! [integer!]"
"int32_t*"                                  "pointer! [integer!]"
"INT64"                                     "int64-value!"
"INT64*"                                    "int64-ptr!"
"int64_t"                                   "int64-value!"
"int64_t*"                                  "int64-ptr!"
"longlong*"                                 "int64-ptr!"
"LPVOID"                                    "pointer! [integer!]"
"LPVOID*"                                   "pointer! [integer!]"
"PGPU_DEVICE"                               "PGPU_DEVICE!"
"Pixmap"                                    "XPixmap!"
"sqlite3*"                                  "sqlite3!"
"sqlite3**"                                 "sqlite3-ptr!"
"sqlite3_backup*"                           "sqlite3-backup!"
"sqlite3_blob*"                             "sqlite3-blob!"
"sqlite3_blob**"                            "sqlite3-blob-ptr!"
"sqlite3_changegroup*"                      "sqlite3-changegroup!"
"sqlite3_changegroup**"                     "sqlite3-changegroup-ptr!"
"sqlite3_changeset_iter*"                   "sqlite3-changeset-iter!"
"sqlite3_changeset_iter**"                  "sqlite3-changeset-iter-ptr!"
"sqlite3_context*"                          "sqlite3-context!"
"sqlite3_int64"                             "int64-value!"
"sqlite3_int64*"                            "int64-ptr!"
"sqlite3_module*"                           "sqlite3_module!"
"sqlite3_mutex*"                            "sqlite3-mutex!"
"sqlite3_rtree_dbl*"                        "sqlite3-rtree-dbl!"
"sqlite3_rtree_geometry*"                   "sqlite3-rtree-geometry!"
"sqlite3_rtree_query_info*"                 "sqlite3-rtree-query-info!"
"sqlite3_session*"                          "sqlite3-session!"
"sqlite3_session**"                         "sqlite3-session-ptr!"
"sqlite3_snapshot*"                         "sqlite3-snapshot!"
"sqlite3_snapshot**"                        "sqlite3-snapshot-ptr!"
"sqlite3_stmt*"                             "sqlite3-stmt!"
"sqlite3_stmt**"                            "sqlite3-stmt-ptr!"
"sqlite3_uint64"                            "uint64-value!"
"sqlite3_value*"                            "sqlite3-value!"
"sqlite3_value**"                           "sqlite3-value-ptr!"
"sqlite3_vfs*"                              "sqlite3-vfs!"
"Status"                                    "XStatus!"
"UINT"                                      "integer!"
"UINT*"                                     "pointer! [integer!]"
"uint32_t"                                  "integer!"
"uint32_t*"                                 "pointer! [integer!]"
"uint64_t"                                  "int64-value!"
"unsigned"                                  "integer!"
"unsignedchar"                              "byte!"
"unsignedchar*"                             "c-string!"
"unsignedchar**"                            "string-ptr!"
"unsignedint"                               "integer!"
"unsignedint*"                              "pointer! [integer!]"
"unsignedlong"                              "integer!"
"unsignedlong*"                             "pointer! [integer!]"
"unsignedlonglong"                          "uint64-value!"
"unsignedlonglong*"                         "uint64-ptr!"
"unsignedshort*"                            "uint16-ptr!"
"USHORT*"                                   "uint16-ptr!"
"VkAllocationCallbacks*"                    "pointer! [integer!]"
"VkInstance"                                "pointer! [integer!]"
"VkPhysicalDevice"                          "pointer! [integer!]"
"VkResult"                                  "integer!"
"VkSurfaceKHR*"                             "pointer! [integer!]"
"void*"                                     "pointer! [byte!]"
"void**"                                    "binary-ptr!"
"void*const*"                               "binary-ptr!"
"Window"                                    "XWindow!"
"XVisualInfo*"                              "XVisualInfo-ptr!"

"RECT_STRUCT"                               "RECT!"
"tagMSG"                                    "MSG!"
"POINT"                                     "POINT!"
"POINTFLOAT"                                "POINTFLOAT!"

]